--------------------------------------------------------
--  DDL for Table BIG_KIND
--------------------------------------------------------

  CREATE TABLE "FARM_DB"."BIG_KIND" 
   (	"BIG_CODE" VARCHAR2(20 BYTE), 
	"BIG_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into FARM_DB.BIG_KIND
SET DEFINE OFF;
Insert into FARM_DB.BIG_KIND (BIG_CODE,BIG_NAME) values ('big 1','big 1 name');
Insert into FARM_DB.BIG_KIND (BIG_CODE,BIG_NAME) values ('big 2','big 2 name');
