--------------------------------------------------------
--  DDL for Table MEDIUM_KIND
--------------------------------------------------------

  CREATE TABLE "FARM_DB"."MEDIUM_KIND" 
   (	"MEDIUM_CODE" VARCHAR2(20 BYTE), 
	"MEDIUM_NAME" VARCHAR2(100 BYTE), 
	"BIG_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into FARM_DB.MEDIUM_KIND
SET DEFINE OFF;
Insert into FARM_DB.MEDIUM_KIND (MEDIUM_CODE,MEDIUM_NAME,BIG_CODE) values ('medium 1','medium 1 name','big 1');
Insert into FARM_DB.MEDIUM_KIND (MEDIUM_CODE,MEDIUM_NAME,BIG_CODE) values ('medium 2','medium 1 name','big 1');
Insert into FARM_DB.MEDIUM_KIND (MEDIUM_CODE,MEDIUM_NAME,BIG_CODE) values ('medium 3','medium 3 name','big 2');
