--------------------------------------------------------
--  DDL for Table SCAN_TABLE
--------------------------------------------------------

  CREATE TABLE "FARM_DB"."SCAN_TABLE" 
   (	"ID_SCAN" VARCHAR2(20 BYTE), 
	"ID_ACTION" VARCHAR2(20 BYTE), 
	"QUANTITY" VARCHAR2(20 BYTE), 
	"PIC1" VARCHAR2(20 BYTE), 
	"PIC2" VARCHAR2(20 BYTE), 
	"PIC3" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into FARM_DB.SCAN_TABLE
SET DEFINE OFF;
