--SELECT * FROM USER_TABLE WHERE USER_NAME = 'USER 1' AND PASSWORD = 'PASSWORD'

--SELECT B.BIG_CODE, M.* FROM BIG_KIND B 
--INNER JOIN MEDIUM_KIND M ON B.BIG_CODE = M.BIG_CODE

--SELECT BIG_CODE Id, BIG_NAME Name FROM BIG_KIND

SELECT MEDIUM_CODE Id, MEDIUM_NAME Name FROM MEDIUM_KIND
